#!/usr/bin/env python2.7

import sys
import os

_APP_PATH = \
    os.path.join(os.path.dirname(__file__), '..', '..', '..')

sys.path.insert(0, os.path.abspath(_APP_PATH))

import logging
import argparse

import pm.config.log
import pm.manifest

_LOGGER = logging.getLogger(__name__)

def _parse_args():
    description = "Print the patch-info data from the given patch."
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument(
        'patch_filepath',
        help='Path filepath')

    args = parser.parse_args()

    return args

def _main():
    args = _parse_args()

    patch_filepath = args.patch_filepath

    m = pm.manifest.Manifest('/dev/null')
    patch_info = m.get_raw_patch_info_from_file(patch_filepath)

    print(patch_info)

if __name__ == '__main__':
    pm.config.log.configure_log()
    _main()
